"""update todo model

Revision ID: 170830d55e58
Revises: a2a46c122d88
Create Date: 2024-08-19 20:45:54.034072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170830d55e58'
down_revision: Union[str, None] = 'a2a46c122d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'group_id')
    # ### end Alembic commands ###
