"""update invite model

Revision ID: a09cd339884b
Revises: c636a65a29e1
Create Date: 2024-08-28 13:57:22.330116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09cd339884b'
down_revision: Union[str, None] = 'c636a65a29e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('group_id', sa.Integer(), nullable=False))
    op.add_column('invites', sa.Column('group_name', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'invites', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_column('invites', 'group_name')
    op.drop_column('invites', 'group_id')
    # ### end Alembic commands ###
